# Tutorial Basics
This the tutorial for learning **numpy**.

## Project overview

**Libraries used:**
- NumPy — array operations


In [ ]:
import numpy as np

In [ ]:
# print the dimension of the array
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

In [6]:
arr = np.array([[1,2,3,4], [6,7,8,9]])
print(arr[:, 1:3])
print("2nd element on 1st row", arr[0, 1])
print("last  element from 2nd dim: ", arr[1, -1])
print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])



[[2 3]
 [7 8]]
2nd element on 1st row 2
last  element from 2nd dim:  9
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [6]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])


6


In [5]:
arr1 = np.array([1, 2, 3, 4])
print(arr1.dtype)
arr2 = np.array(['apple', "pear","banana"])
print(arr2.dtype)

int64
<U6


In [3]:
arr = np.array([1,2,3,4,5], dtype="U")
print(arr)
print(arr.dtype)

['1' '2' '3' '4' '5']
<U1


In [7]:
#copying the array into a new array and change the data type of array
arr = np.array([1.1, 2.1, 3.1])
print(arr.dtype)
print(arr)
new_arr = arr.astype("i")
print(new_arr.dtype)
print(new_arr)

float64
[1.1 2.1 3.1]
int32
[1 2 3]


In [10]:
arr = np.array([1, 0, 3])

new_arr = arr.astype(bool)

print(new_arr)
print(new_arr.dtype)

[ True False  True]
bool


In [119]:
#copying array, when changing the original array, the copied one does not change.
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [117]:
# view: make tha view, change the original array, affects the viewed array too
arr = np.array([1,34,3,34,45])
x = arr.view()
arr[0] = 23
print(arr)
print(x)

[23  2  3 34 45]
[23  2  3 34 45]


In [13]:
# copies owns the data, and views does not own the data, but we can check this.
# Every NumPy array has the attribute base that returns None if the array owns the data.
# Otherwise, the base  attribute refers to the original object.
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base) # the copy returns None
print(y.base) # the view returns the original array.

None
[1 2 3 4 5]


In [12]:
# shape of an array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr1 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr2 = np.array([1,34,3,34,45])
print(arr.shape) # returns a tuple (2,4) which means 2 rows and 4 columns
print(arr1.shape)
print(arr2.shape)

(2, 4)
(2, 2, 3)
(5,)


### ndim
Integers at every index tells about the number of elements the corresponding dimension has.<br>
Create an array with 5 dimensions using `ndmin` using a vector with values 1,2,3,4 and verify that last dimension has value 4.<br>
In the example below at index-4 we have value 4, so we can say that 5th ( 4 + 1 th) dimension has 4 elements.





In [36]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


### Reshaping Arrays
By reshaping we can add or remove dimensions or change number of elements in each dimension.



In [61]:
# from 1D to 2D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
# The outermost dimension will have 4 arrays, each with 3 elements
new_arr = arr.reshape(4, 3)
print(new_arr)
# reshape returns a view
print(new_arr.base)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [8]:
# from 1D to 3D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
new_arr = arr.reshape(2, 3, 2)
print(new_arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [13]:
# we are allowed to have one "unknown" dimension.
# Meaning that we do not have to specify an exact number for one of the dimensions in the reshape method.
# Pass -1 as the value, and NumPy will calculate this number for you.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
new_arr = arr.reshape(2, 2, -1)
print(new_arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
# Flattening array means converting a multidimensional array into a 1D array.
# We can use reshape(-1) to do this.

arr1 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr1.reshape(-1))


[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Iterating Arrays
Iterating means going through elements one by one.<br>
As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.<br>




In [18]:
# If we iterate on a 1-D array it will go through each element one by one.
arr = np.array([1,2,3,34,5,5,5])
for i in arr:
    print(i)

1
2
3
34
5
5
5


In [20]:
# Iterate on each scalar element of the 2-D array:
arr = np.array([[1,2,3,4], [6,7,8,9]])
for i in arr:
    for j in i:
        print(j)

1
2
3
4
6
7
8
9


In [29]:
# iteration using nditer()
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [14]:
# iterating arras with different data types
# NumPy does not change the data type of the element in-place (where the element is in array) so
# it needs some other space to perform this action, that extra space is called buffer, and in
# order to enable it in nditer() we pass flags=['buffered'].
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr, flags=['buffered'], op_dtypes='S'):
  print(x)

1
2
3
4
5
6
7
8


In [37]:
# iterating with different step size
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [39]:
# printing elements with their corresponding index we use ndenumerate()
arr = np.array([1,2,3,4,54,5])
for index, i in np.ndenumerate(arr):
    print(f"the index is {index} and the element is {i}")

the index is (0,) and the element is 1
the index is (1,) and the element is 2
the index is (2,) and the element is 3
the index is (3,) and the element is 4
the index is (4,) and the element is 54
the index is (5,) and the element is 5


In [43]:
# enumerate in 2D array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


## Joining NumPy Arrays
Joining means putting contents of two or more arrays in a single array.<br>
We pass a sequence of arrays that we want to join to the `concatenate()` function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [46]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# vertical join, the number of columns must match, here the default
# axis=0 which is vertical join
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [15]:
# we can also join along the axis explicitly based on the ndim of the two arrays.
# in 2D array
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)
print(np.concatenate((arr[0], arr[1])))

[[1 2 5 6]
 [3 4 7 8]]
[1 2 5 6 3 4 7 8]


## Creating the Filter Array

In [56]:
arr = np.array([41, 42, 43, 44])
filter_array = [] # boolean index list
for element in arr:
    if element> 42: # we can also return the even element by element % 2 == 0
        filter_array.append(True)
    else:
        filter_array.append(False)

new_arr = arr[filter_array]
print(filter_array)
print(new_arr)


[False, False, True, True]
[43 44]


In [58]:
# easy way of filtering
arr = np.array([41, 42, 43, 44])
filter_array = arr > 42
new_arr = arr[filter_array]
print(filter_array)
print(new_arr)
print(arr)

[False False  True  True]
[43 44]
[41 42 43 44]


### Splitting NumPy Arrays
Splitting is reverse operation of Joining,<br>
Joining merges multiple arrays into one and Splitting breaks one array into multiple.<br>
We use `split()` for splitting arrays, we pass it the array we want to split and the number of splits.

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = np.split(arr, 3)
print(new_arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [22]:
# for the arrays that has fewer elements that is required, the split() will fail but we use the
# array_split().
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = np.array_split(arr, 4)
print(new_arr)
# we can also access them like below

print(new_arr[0])
print(new_arr[1])
print(new_arr[2])

[array([1, 2]), array([3, 4]), array([5]), array([6])]
[1 2]
[3 4]
[5]


In [25]:
# splitting 2D arrays
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
new_arr = np.array_split(arr, 3)
print(new_arr)


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


## Numppy Searching Arrays
we can also search for a certain value in the array using the `where()` method and it returns the index of that value.

In [39]:
arr = np.array([1, 2, 3 , 5, 6, 7, 9, 3, 2, 3])
x = np. where(arr == 3)
print(x)

(array([2, 7, 9]),)


In [41]:
arr = np.array([10, 14, 93, 41, 8, 7])
print(np.where(arr % 2 == 1)) # find the indexes where the values are odd
print(np.where(arr % 2 == 0)) # find the indexes where the values are even

(array([2, 3, 5]),)
(array([0, 1, 4]),)
