In [1]:
from numpy import random
import numpy as np


In [2]:
x = random.randint(100) # generate a random integer between 0 and 100
print(x)
print(random.rand()) # random between 0 and 1
print(random.randint(100, size=5)) # generate 1D array with 5 elements between 0 and 100
print(random.randint(100, size=(3, 5))) # 2D array with 3 rows and 5 columns between 0 and 100
print(random.rand(5)) # 1D array with 5 random float elements
print(random.rand(3, 5)) # 2D array, 3 rows, 5 columns, th elements are float.

33
0.6052925740375713
[91  6 59 29 49]
[[60 53 92 91 20]
 [39  8 67 68 80]
 [41 58 84 93 28]]
[0.59495339 0.2353934  0.23825771 0.15045722 0.84753497]
[[0.86877461 0.30750819 0.80901128 0.46378619 0.68498603]
 [0.85438834 0.91068457 0.32420276 0.99166074 0.77290477]
 [0.38558535 0.40106586 0.51542361 0.82871296 0.9728031 ]]


### Generate Random Number From Array
The `choice()` method allows you to generate a random value based on an array of values.<br>
The `choice()` method takes an array as a parameter and randomly returns one of the values.

In [66]:
x = random.choice([3, 5, 7, 9])
print(x)
print(random.choice([1, 3, 5, 7, 9], size=(3, 5)))# to generate a random array of values

3
[[5 9 7 3 3]
 [5 1 9 7 7]
 [3 3 1 7 1]]


### Random Distribution

In [70]:
# p is the probability of each of the numbers in the array
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=100)
print(x)
print(random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5)))

[5 7 7 5 7 5 7 7 7 3 5 5 5 7 7 7 7 7 7 5 5 7 5 5 3 5 7 5 5 7 5 7 5 5 3 7 5
 7 7 5 7 5 7 7 7 7 7 3 7 5 5 5 7 5 7 7 7 5 7 5 7 7 7 3 7 7 7 7 7 7 5 7 7 7
 7 5 7 5 7 3 7 7 7 7 5 3 7 5 7 5 7 7 7 7 7 7 7 7 5 5]
[[3 7 7 7 7]
 [3 5 5 5 7]
 [7 3 7 5 5]]


### Shuffling arrays
we can shuffle the elements of the array using the `shufle()` method.

In [90]:
arr = np.array([1, 2, 3, 4, 5])
random.shuffle(arr)
print(arr)

[5 3 1 4 2]


### Generating Permutation of Arrays
we can generate the random permutation of the elements of the array using the `permuation()` method.

In [92]:
arr = np.array([1, 2, 3, 4, 5])
print(random.permutation(arr))

[5 2 3 1 4]
