In [1]:
from numpy import random
import numpy as np


In [2]:
x = random.randint(100) # generate a random integer between 0 and 100
print(x)
print(random.rand()) # random between 0 and 1
print(random.randint(100, size=5)) # generate 1D array with 5 elements between 0 and 100
print(random.randint(100, size=(3, 5))) # 2D array with 3 rows and 5 columns between 0 and 100
print(random.rand(5)) # 1D array with 5 random float elements
print(random.rand(3, 5)) # 2D array, 3 rows, 5 columns, th elements are float.

33
0.6052925740375713
[91  6 59 29 49]
[[60 53 92 91 20]
 [39  8 67 68 80]
 [41 58 84 93 28]]
[0.59495339 0.2353934  0.23825771 0.15045722 0.84753497]
[[0.86877461 0.30750819 0.80901128 0.46378619 0.68498603]
 [0.85438834 0.91068457 0.32420276 0.99166074 0.77290477]
 [0.38558535 0.40106586 0.51542361 0.82871296 0.9728031 ]]


### Generate Random Number From Array
The `choice()` method allows you to generate a random value based on an array of values.<br>
The `choice()` method takes an array as a parameter and randomly returns one of the values.

In [66]:
x = random.choice([3, 5, 7, 9])
print(x)
print(random.choice([1, 3, 5, 7, 9], size=(3, 5)))# to generate a random array of values

3
[[5 9 7 3 3]
 [5 1 9 7 7]
 [3 3 1 7 1]]


### Random Distribution

In [70]:
# p is the probability of each of the numbers in the array
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=100)
print(x)
print(random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5)))

[5 7 7 5 7 5 7 7 7 3 5 5 5 7 7 7 7 7 7 5 5 7 5 5 3 5 7 5 5 7 5 7 5 5 3 7 5
 7 7 5 7 5 7 7 7 7 7 3 7 5 5 5 7 5 7 7 7 5 7 5 7 7 7 3 7 7 7 7 7 7 5 7 7 7
 7 5 7 5 7 3 7 7 7 7 5 3 7 5 7 5 7 7 7 7 7 7 7 7 5 5]
[[3 7 7 7 7]
 [3 5 5 5 7]
 [7 3 7 5 5]]


### Shuffling arrays
we can shuffle the elements of the array using the `shufle()` method.

In [90]:
arr = np.array([1, 2, 3, 4, 5])
random.shuffle(arr)
print(arr)

[5 3 1 4 2]


### Generating Permutation of Arrays
we can generate the random permutation of the elements of the array using the `permuation()` method.

In [92]:
arr = np.array([1, 2, 3, 4, 5])
print(random.permutation(arr))

[5 2 3 1 4]


### Calculating a Confidence Interval of a Population Proportion
With Python, use the scipy and math libraries to calculate the confidence interval for an estimated proportion.

Here, the sample size is 30 and the occurrences is 6.

In [5]:
import scipy.stats as stats
import math
# Specify sample occurrences (x), sample size (n) and confidence level
x = 6
n = 30
confidence_level = 0.95
# Calculate the point estimate or proportion, the critical z-value, the standard error, and the margin of error
proportion = x / n
critical_z = stats.norm.ppf((1 + confidence_level) / 2)
standard_error = math.sqrt((proportion*(1-proportion)/n))
margin_of_error = critical_z * standard_error

# Calculate the lower and upper bound of the confidence interval
lower_bound = proportion - margin_of_error
upper_bound = proportion + margin_of_error

# Print the results
print("Point Estimate or proportion: {:.3f}".format(proportion))
print("Critical Z-value: {:.3f}".format(critical_z))
print("Margin of Error: {:.3f}".format(margin_of_error))
print("Confidence Interval: [{:.3f},{:.3f}]".format(lower_bound,upper_bound))
print("The {:.1%} confidence interval for the population proportion is:".format(confidence_level))
print("between {:.3f} and {:.3f}".format(lower_bound,upper_bound))

Point Estimate or proportion: 0.200
Critical Z-value: 1.960
Margin of Error: 0.143
Confidence Interval: [0.057,0.343]
The 95.0% confidence interval for the population proportion is:
between 0.057 and 0.343


### Calculating a Confidence Interval of Student's T Distribution
Here, the sample size is 30, sample mean is 62.1 and sample standard deviation is 13.46.



In [6]:
import scipy.stats as stats
import math

# Specify sample mean (x_bar), sample standard deviation (s), sample size (n) and confidence level
x_bar = 62.1
s = 13.46
n = 30
confidence_level = 0.95

# Calculate, degrees of freedom (df), the critical t-value, and the margin of error
df = n - 1
standard_error = s/math.sqrt(n)
critical_t = stats.t.ppf((1 + confidence_level) / 2, df)
margin_of_error = critical_t * standard_error

# Calculate the lower and upper bound of the confidence interval
lower_bound = x_bar - margin_of_error
upper_bound = x_bar + margin_of_error

# Print the results
print("Critical t-value: {:.3f}".format(critical_t))
print("Margin of Error: {:.3f}".format(margin_of_error))
print("Confidence Interval: [{:.3f},{:.3f}]".format(lower_bound,upper_bound))
print("The {:.1%} confidence interval for the population mean is:".format(confidence_level))
print("between {:.3f} and {:.3f}".format(lower_bound,upper_bound))

Critical t-value: 2.045
Margin of Error: 5.026
Confidence Interval: [57.074,67.126]
The 95.0% confidence interval for the population mean is:
between 57.074 and 67.126
