In [14]:
from hmac import new

import numpy as np

In [34]:
arr = np.array([[1,2,3,4], [6,7,8,9]])
print("2nd element on 1st row", arr[0, 1])
print("last  element from 2nd dim: ", arr[1, -1])
print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

2nd element on 1st row 2
last  element from 2nd dim:  9
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [35]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])


6


In [94]:
arr1 = np.array([1, 2, 3, 4])
print(arr1.dtype)
arr2 = np.array(['apple', "pear","banana"])
print(arr2.dtype)

int64
<U6


In [107]:
arr = np.array([1,2,3,4,5], dtype="U")
print(arr)
print(arr.dtype)

['1' '2' '3' '4' '5']
<U1


In [113]:
#copying the array into a new array and change the data type of array
arr = np.array([1.1, 2.1, 3.1])
print(arr.dtype)

new_arr = arr.astype("i")
print(new_arr.dtype)

float64
int32


In [118]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [119]:
#copying array, when changing the original array, the copied one does not change.
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [117]:
# view: make tha view, change the original array, affects the viewed array too
arr = np.array([1,34,3,34,45])
x = arr.view()
arr[0] = 23
print(arr)
print(x)

[23  2  3 34 45]
[23  2  3 34 45]


In [123]:
# copies owns the data, and views does not own the data, but we can check this.
# Every NumPy array has the attribute base that returns None if the array owns the data.
# Otherwise, the base  attribute refers to the original object.
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base) # the copy returns None
print(y.base) # the view returns the original array.

None
[1 2 3 4 5]


In [126]:
# shape of an array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape) # returns a tuple (2,4) which means 2 rows and 4 collumns

(2, 4)


In [16]:
x = [1,2,3,43,4]

print(x)

[1, 2, 3, 43, 4]


In [19]:
y = [x.index(2)]
print(y)

[1]


In [24]:
queue = [0]
visited = [False] * 3
visited[queue[0]] = True
print(visited)
print(queue)


[True, False, False]
[0]
